apiVersion: v1 
kind: Service 
metadata:
  name: service-nodeport
  namespace: my-app
spec:   
  type: NodePort
  selector:
    app: my-app
    apptype: frontend
  ports: 
    - targetPort: 80 
      port: 80
      nodePort: 30808